dist: bionic
language: go
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - wget -qO - http://packages.confluent.io/deb/3.1/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4 stable main"
  - sudo apt-get update
  - sudo apt-get install librdkafka-dev

install:
  - export GO111MODULE=on
  - GO111MODULE=off go get github.com/mitchellh/gox

script:
  - go test -mod=vendor -v -race ./...
  - if [ "${LATEST}" = "true" ]; then gox -ldflags "-s -w -X github.com/etf1/kafka-mongo-watcher/config.AppVersion=$TRAVIS_TAG" -os="linux" -arch="amd64" -output="kafka-mongo-watcher-{{.OS}}-{{.Arch}}"  -verbose ./...; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - kafka-mongo-watcher-linux-amd64
  on:
    repo: etf1/kafka-mongo-watcher
    tags: true
    condition: $LATEST = true
