version: '3.7'

services:
  mongo-primary:
    hostname: mongo-primary
    container_name: mongo-primary
    image: bitnami/mongodb:4.2
    restart: always
    expose:
      - 27011
    ports:
      - 27011:27011
    environment:
        MONGODB_PORT_NUMBER: 27011
        MONGODB_ADVERTISED_HOSTNAME: mongo-primary
        MONGODB_REPLICA_SET_MODE: primary
        MONGODB_REPLICA_SET_KEY: replicasetkey123
        MONGODB_ROOT_PASSWORD: toor

  mongo-secondary:
    hostname: mongo-secondary
    container_name: mongo-secondary
    image: bitnami/mongodb:4.2
    restart: always
    expose:
      - 27012
    ports:
      - 27012:27012
    environment:
        MONGODB_PORT_NUMBER: 27012
        MONGODB_PRIMARY_HOST: mongo-primary
        MONGODB_PRIMARY_PORT_NUMBER: 27011
        MONGODB_ADVERTISED_HOSTNAME: mongo-secondary
        MONGODB_REPLICA_SET_MODE: secondary
        MONGODB_REPLICA_SET_KEY: replicasetkey123
        MONGODB_PRIMARY_ROOT_PASSWORD: toor

  mongo-arbiter:
    hostname: mongo-arbiter
    container_name: mongo-arbiter
    image: bitnami/mongodb:4.2
    restart: always
    expose:
      - 27013
    ports:
      - 27013:27013
    environment:
        MONGODB_PORT_NUMBER: 27013
        MONGODB_PRIMARY_HOST: mongo-primary
        MONGODB_PRIMARY_PORT_NUMBER: 27011
        MONGODB_ADVERTISED_HOSTNAME: mongo-arbiter
        MONGODB_REPLICA_SET_MODE: arbiter
        MONGODB_REPLICA_SET_KEY: replicasetkey123
        MONGODB_PRIMARY_ROOT_PASSWORD: toor
