// Code generated by MockGen. DO NOT EDIT.
// Source: internal/kafka/producer.go

package kafka

import (
	gomock "github.com/golang/mock/gomock"
	kafka "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"
	reflect "reflect"
)

// MockKafkaProducer is a mock of KafkaProducer interface
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return _m.recorder
}

// Close mocks base method
func (_m *MockKafkaProducer) Close() {
	_m.ctrl.Call(_m, "Close")
}

// Close indicates an expected call of Close
func (_mr *MockKafkaProducerMockRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Close", reflect.TypeOf((*MockKafkaProducer)(nil).Close))
}

// Events mocks base method
func (_m *MockKafkaProducer) Events() chan kafka.Event {
	ret := _m.ctrl.Call(_m, "Events")
	ret0, _ := ret[0].(chan kafka.Event)
	return ret0
}

// Events indicates an expected call of Events
func (_mr *MockKafkaProducerMockRecorder) Events() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Events", reflect.TypeOf((*MockKafkaProducer)(nil).Events))
}

// Produce mocks base method
func (_m *MockKafkaProducer) Produce(msg *kafka.Message, deliveryChan chan kafka.Event) error {
	ret := _m.ctrl.Call(_m, "Produce", msg, deliveryChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce
func (_mr *MockKafkaProducerMockRecorder) Produce(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Produce", reflect.TypeOf((*MockKafkaProducer)(nil).Produce), arg0, arg1)
}
