// Code generated by MockGen. DO NOT EDIT.
// Source: internal/mongo/client.go

package mongo

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDriverCursor is a mock of DriverCursor interface
type MockDriverCursor struct {
	ctrl     *gomock.Controller
	recorder *MockDriverCursorMockRecorder
}

// MockDriverCursorMockRecorder is the mock recorder for MockDriverCursor
type MockDriverCursorMockRecorder struct {
	mock *MockDriverCursor
}

// NewMockDriverCursor creates a new mock instance
func NewMockDriverCursor(ctrl *gomock.Controller) *MockDriverCursor {
	mock := &MockDriverCursor{ctrl: ctrl}
	mock.recorder = &MockDriverCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDriverCursor) EXPECT() *MockDriverCursorMockRecorder {
	return _m.recorder
}

// Decode mocks base method
func (_m *MockDriverCursor) Decode(val interface{}) error {
	ret := _m.ctrl.Call(_m, "Decode", val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode
func (_mr *MockDriverCursorMockRecorder) Decode(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Decode", reflect.TypeOf((*MockDriverCursor)(nil).Decode), arg0)
}

// Next mocks base method
func (_m *MockDriverCursor) Next(ctx context.Context) bool {
	ret := _m.ctrl.Call(_m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next
func (_mr *MockDriverCursorMockRecorder) Next(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Next", reflect.TypeOf((*MockDriverCursor)(nil).Next), arg0)
}

// Close mocks base method
func (_m *MockDriverCursor) Close(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (_mr *MockDriverCursorMockRecorder) Close(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Close", reflect.TypeOf((*MockDriverCursor)(nil).Close), arg0)
}

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// Replay mocks base method
func (_m *MockClient) Replay(ctx context.Context, collection CollectionAdapter) (chan *WatchItem, error) {
	ret := _m.ctrl.Call(_m, "Replay", ctx, collection)
	ret0, _ := ret[0].(chan *WatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replay indicates an expected call of Replay
func (_mr *MockClientMockRecorder) Replay(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Replay", reflect.TypeOf((*MockClient)(nil).Replay), arg0, arg1)
}

// Watch mocks base method
func (_m *MockClient) Watch(ctx context.Context, collection CollectionAdapter) (chan *WatchItem, error) {
	ret := _m.ctrl.Call(_m, "Watch", ctx, collection)
	ret0, _ := ret[0].(chan *WatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch
func (_mr *MockClientMockRecorder) Watch(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Watch", reflect.TypeOf((*MockClient)(nil).Watch), arg0, arg1)
}
