// Code generated by MockGen. DO NOT EDIT.
// Source: internal/mongo/collection.go

// Package mongo is a generated GoMock package.
package mongo

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	options "go.mongodb.org/mongo-driver/mongo/options"
	reflect "reflect"
)

// MockDriverCursor is a mock of DriverCursor interface
type MockDriverCursor struct {
	ctrl     *gomock.Controller
	recorder *MockDriverCursorMockRecorder
}

// MockDriverCursorMockRecorder is the mock recorder for MockDriverCursor
type MockDriverCursorMockRecorder struct {
	mock *MockDriverCursor
}

// NewMockDriverCursor creates a new mock instance
func NewMockDriverCursor(ctrl *gomock.Controller) *MockDriverCursor {
	mock := &MockDriverCursor{ctrl: ctrl}
	mock.recorder = &MockDriverCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDriverCursor) EXPECT() *MockDriverCursorMockRecorder {
	return m.recorder
}

// Decode mocks base method
func (m *MockDriverCursor) Decode(val interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode
func (mr *MockDriverCursorMockRecorder) Decode(val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockDriverCursor)(nil).Decode), val)
}

// Next mocks base method
func (m *MockDriverCursor) Next(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next
func (mr *MockDriverCursorMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockDriverCursor)(nil).Next), ctx)
}

// Close mocks base method
func (m *MockDriverCursor) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockDriverCursorMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDriverCursor)(nil).Close), ctx)
}

// MockDriverDatabase is a mock of DriverDatabase interface
type MockDriverDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDriverDatabaseMockRecorder
}

// MockDriverDatabaseMockRecorder is the mock recorder for MockDriverDatabase
type MockDriverDatabaseMockRecorder struct {
	mock *MockDriverDatabase
}

// NewMockDriverDatabase creates a new mock instance
func NewMockDriverDatabase(ctrl *gomock.Controller) *MockDriverDatabase {
	mock := &MockDriverDatabase{ctrl: ctrl}
	mock.recorder = &MockDriverDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDriverDatabase) EXPECT() *MockDriverDatabaseMockRecorder {
	return m.recorder
}

// Name mocks base method
func (m *MockDriverDatabase) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (mr *MockDriverDatabaseMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDriverDatabase)(nil).Name))
}

// MockCollectionAdapter is a mock of CollectionAdapter interface
type MockCollectionAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionAdapterMockRecorder
}

// MockCollectionAdapterMockRecorder is the mock recorder for MockCollectionAdapter
type MockCollectionAdapterMockRecorder struct {
	mock *MockCollectionAdapter
}

// NewMockCollectionAdapter creates a new mock instance
func NewMockCollectionAdapter(ctrl *gomock.Controller) *MockCollectionAdapter {
	mock := &MockCollectionAdapter{ctrl: ctrl}
	mock.recorder = &MockCollectionAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCollectionAdapter) EXPECT() *MockCollectionAdapterMockRecorder {
	return m.recorder
}

// Aggregate mocks base method
func (m *MockCollectionAdapter) Aggregate(ctx context.Context, pipeline interface{}, opts ...*options.AggregateOptions) (AggregateCursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, pipeline}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Aggregate", varargs...)
	ret0, _ := ret[0].(AggregateCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate
func (mr *MockCollectionAdapterMockRecorder) Aggregate(ctx, pipeline interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, pipeline}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockCollectionAdapter)(nil).Aggregate), varargs...)
}

// Database mocks base method
func (m *MockCollectionAdapter) Database() DriverDatabase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Database")
	ret0, _ := ret[0].(DriverDatabase)
	return ret0
}

// Database indicates an expected call of Database
func (mr *MockCollectionAdapterMockRecorder) Database() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Database", reflect.TypeOf((*MockCollectionAdapter)(nil).Database))
}

// Watch mocks base method
func (m *MockCollectionAdapter) Watch(ctx context.Context, pipeline interface{}, opts ...*options.ChangeStreamOptions) (StreamCursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, pipeline}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(StreamCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch
func (mr *MockCollectionAdapterMockRecorder) Watch(ctx, pipeline interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, pipeline}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockCollectionAdapter)(nil).Watch), varargs...)
}

// Name mocks base method
func (m *MockCollectionAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (mr *MockCollectionAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCollectionAdapter)(nil).Name))
}
