name: Push

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.14', '1.15', '1.16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install go dependencies & run tests
        shell: script -q -e -c "bash {0}"
        run: |
          go get -t -v ./...
          go test -count=1 -v -cover ./...
