name: Push

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.22' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run tests
        shell: script -q -e -c "bash {0}"
        run: go test -count=1 -v -cover ./...
